In [12]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [13]:
df  = pd.read_csv(r'demo_text_data.csv')
df

   id                                             text category
0   1               Hello!!! This is the FIRST text :)        A
1   2  NLP is amazing, isn't it??? Running runs ran...        B
2   3        Cleaning #data is IMPORTANT!!! 100% sure.        A

In [14]:
df.iloc[0,1]

'Hello!!! This is the FIRST text :)'

In [15]:
df.iloc[2,2]

'A'

In [16]:
text = df.iloc[0,1]
re.sub(r'[^a-zA-Z\s]', '', str(text))

'Hello This is the FIRST text '

In [17]:
df["text"] = df["text"].str.replace(r'[^a-zA-Z\s]', '', regex=True)
df

   id                                     text category
0   1            Hello This is the FIRST text         A
1   2  NLP is amazing isnt it Running runs ran        B
2   3         Cleaning data is IMPORTANT  sure        A

In [6]:
df["clean_text"] = df["text"].str.replace(r'[^a-zA-Z\s]', '', regex=True)
df["clean_text"] = df["clean_text"].str.lower()
df

,id,text,category,clean_text
0,1,Hello!!! This is the FIRST text :),A,hello this is the first text
1,2,"NLP is amazing, isn't it??? Running runs ran...",B,nlp is amazing isnt it running runs ran
2,3,Cleaning #data is IMPORTANT!!! 100% sure.,A,cleaning data is important sure

In [7]:
df["tokens"] = df["clean_text"].apply(word_tokenize)
df

,id,text,category,clean_text,tokens
0,1,Hello!!! This is the FIRST text :),A,hello this is the first text,"[hello, this, is, the, first, text]"
1,2,"NLP is amazing, isn't it??? Running runs ran...",B,nlp is amazing isnt it running runs ran,"[nlp, is, amazing, isnt, it, running, runs, ran]"
2,3,Cleaning #data is IMPORTANT!!! 100% sure.,A,cleaning data is important sure,"[cleaning, data, is, important, sure]"

In [8]:
stop_words = set(stopwords.words('english'))

df["no_stopwords"] = df["tokens"].apply(
    lambda words: [w for w in words if w not in stop_words]
)

df

,id,text,category,clean_text,tokens,no_stopwords
0,1,Hello!!! This is the FIRST text :),A,hello this is the first text,"[hello, this, is, the, first, text]","[hello, first, text]"
1,2,"NLP is amazing, isn't it??? Running runs ran...",B,nlp is amazing isnt it running runs ran,"[nlp, is, amazing, isnt, it, running, runs, ran]","[nlp, amazing, isnt, running, runs, ran]"
2,3,Cleaning #data is IMPORTANT!!! 100% sure.,A,cleaning data is important sure,"[cleaning, data, is, important, sure]","[cleaning, data, important, sure]"

In [18]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [9]:
stemmer = PorterStemmer()

df["stemmed"] = df["no_stopwords"].apply(
    lambda words: [stemmer.stem(w) for w in words]
)
df

,id,text,category,clean_text,tokens,no_stopwords,stemmed
0,1,Hello!!! This is the FIRST text :),A,hello this is the first text,"[hello, this, is, the, first, text]","[hello, first, text]","[hello, first, text]"
1,2,"NLP is amazing, isn't it??? Running runs ran...",B,nlp is amazing isnt it running runs ran,"[nlp, is, amazing, isnt, it, running, runs, ran]","[nlp, amazing, isnt, running, runs, ran]","[nlp, amaz, isnt, run, run, ran]"
2,3,Cleaning #data is IMPORTANT!!! 100% sure.,A,cleaning data is important sure,"[cleaning, data, is, important, sure]","[cleaning, data, important, sure]","[clean, data, import, sure]"

In [10]:
lemmatizer = WordNetLemmatizer()

df["lemmatized"] = df["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(w) for w in words]
)
df

,id,text,category,clean_text,tokens,no_stopwords,stemmed,lemmatized
0,1,Hello!!! This is the FIRST text :),A,hello this is the first text,"[hello, this, is, the, first, text]","[hello, first, text]","[hello, first, text]","[hello, first, text]"
1,2,"NLP is amazing, isn't it??? Running runs ran...",B,nlp is amazing isnt it running runs ran,"[nlp, is, amazing, isnt, it, running, runs, ran]","[nlp, amazing, isnt, running, runs, ran]","[nlp, amaz, isnt, run, run, ran]","[nlp, amazing, isnt, running, run, ran]"
2,3,Cleaning #data is IMPORTANT!!! 100% sure.,A,cleaning data is important sure,"[cleaning, data, is, important, sure]","[cleaning, data, important, sure]","[clean, data, import, sure]","[cleaning, data, important, sure]"

# Code1

## code2

### code

#### code